version: '2'
services:
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        restart: always

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=mysqldb-password123
            - MYSQL_USER=mysqldb123
            - MYSQL_PASSWORD=mysqldb-password123
            - MYSQL_DATABASE=mysqldb123
        ports:
            - "3306:3306"
        restart: always

    mariadb:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=mariadb-password123
            - MYSQL_USER=mariadb123
            - MYSQL_PASSWORD=mariadb-password123
            - MYSQL_DATABASE=mariadb123
        ports:
            - "3307:3306"
        restart: always